try {
  const result = someUnidefiendVariable + 79
  console.log(result)
} catch (error) {
  console.log("Error occured ", error.message)
}
